components/Chat/index.vue
Fixes tts so it can be easily reset, adds a function that gets called on toggle change event to cancel the last tts message so it can work again.
=> Fix tts to reset on toggle

components/Chat/ViewerList.vue, components/Chat/index.vue
This PR introduces a `/ignorelist` command to display list of ignored users.
Also adds confirmation messages to both `/ignore` and `/unignore` commands so users know the command was successful.
=> [FEAT] Ignore List Command

components/FollowButton.vue, pages/_watch.vue, plugins/firebase.js
Initial test support for following streamers
=> Feat followers

components/Chat/index.vue
Add ability to ignore an entire channel
=> Create ignore channel command

assets/style/app.styl, assets/style/variables.styl, components/Chat/ChatMessage.vue, components/Chat/ChatPoll.vue, components/Chat/ChatPollVote.vue, components/Chat/ViewerList.vue, components/Chat/index.vue, components/FollowButton.vue, components/LoginDialog/index.vue, components/Notifications/index.vue, components/Payment/braintree-drop-in.vue, components/Payment/v-braintree.vue, components/User.vue, components/UserList.vue, components/VueMarkdown.vue, layouts/barebones.vue, layouts/default.vue, nuxt.config.js, package-lock.json, package.json, pages/_watch.vue, pages/index.vue, pages/login.vue, pages/profile.vue, pages/report.vue, pages/streamers.vue, plugins/vuetify.js, vuetify.options.js
Update UI components to Vuetify 2.X
Misc. performance and layout improvements.
=> Vuetify Upgrade

components/Chat/ChatPollVote.vue, components/Chat/index.vue, components/Notifications/index.vue, layouts/barebones.vue, package.json, pages/_watch.vue, pages/index.vue
This was created to target issues related to SSR errors on initial page load for mobile devices, but includes some general cleanup and refactoring as well.
=> SSR Related Fixes

components/Chat/ChatInput.vue, components/Chat/ChatMessage.vue, components/Chat/ChatMessages.vue, components/Chat/ChatSettings.vue, components/Chat/ViewerList.vue, components/Chat/index.vue, components/Notifications/index.vue, components/User.vue, components/UserList.vue, package.json, store/chat.js
This redesigns the chat input, fixes a few chat related bugs, and improves performance.
Bug Fixes:
- Deleted user tags sometimes reappear when clicking on avatars
- Fix autoscroll logic
- Do not use `scrollIntoView` for autoscrolling
- Do not autoscroll the entire webpage (homepage issue)
Components Isolated:
- Chat Input
- Chat Messages
- Chat Settings
Performance Improvements:
- Convert chat container to functional component
- Utilize store for chat settings and message
- Use `will-change: transform` to separate out layers
- Improve autoscroll function
- Remove vuetify components from chat message
- Load components asynchronously
- Reduce template complexity
Features:
- Chat Input UX Updated
- Chat Settings moved to bottom of panel
- Make Chat Input Clearable
Primary Goals:
- Improve …
=> Improve Chat UX

components/BannerVideo.vue, components/Chat/ChatMessages.vue, components/Chat/index.vue, components/FollowButton.vue, layouts/barebones.vue, layouts/default.vue, package-lock.json, package.json, plugins/vuetify.js
Upgrade to Nuxt v2.10.2
Fix some issues with chat connectivity.
Some performance improvements.
Some styling improvements.
Some general bug fixes.
=> Nuxt 2.10.2

assets/style/app.scss, components/Chat/index.vue, components/Overlay/ChatOverlayInfoCards.vue, nuxt.config.js, package-lock.json, package.json, pages/profile.vue
=> 🍞 Add Toast

components/Chat/ChatInput.vue, components/Chat/ChatSettings.vue, components/Chat/ViewerList.vue, components/Chat/index.vue, components/FollowButton.vue, components/LoginDialog/index.vue, components/Notifications/index.vue, components/Overlay/ChatOverlayDialog.vue, components/Payment/v-braintree.vue, components/StreamGrid.vue, components/User.vue, components/UserList.vue, layouts/default.vue, middleware/auth.js, middleware/not-auth.js, nuxt.config.js, package-lock.json, package.json, pages/_watch.vue, pages/login.vue, pages/overlay/chat/index.vue, pages/profile.vue, pages/signout.vue, pages/streamers.vue, pages/streamkey.vue, store/chat.js, store/index.js, store/user.js
Refactor the Vuex store modules.
Fix SSR by injecting Vuetify CSS sheet.
General code cleanup.
=> Upgrade Store Modules, Fix SSR

assets/js/time-ago.js, components/Channel/StreamArchives.vue, components/Notifications/index.vue
Create common utility library `timeAgo` for displaying dates as `# minutes ago` etc.
=> Create timeAgo library for improved timestamps

components/ShareStream.vue
Adds cache busting to share mechanism.
Inserts a unique timestamp to shared links (updated every 10 minutes) to prevent social media networks from using cached data when creating rich embeds.
Also fixes copy button since vue-clipboard2 seems to fail when used in a popup dialog.
=> Add cache busting to shared links

components/Admin/ArchiveManager.vue, components/Admin/Reports.vue, components/Admin/StreamManager.vue, components/LoginDialog/index.vue, components/User.vue, middleware/admin.js, pages/_watch.vue, pages/admin.vue, pages/login.vue, pages/protected.vue, plugins/firebase.js, store/index.js
Creates an admin panel at `/admin` with various portals.
This route is protected by the new `admin` middleware which checks a user's `role`. Users with the role `admin` are allowed to view the portal, while non-admins are redirected to `/protected`.
At this time, no portals are functional, but this PR is just for basic implementation. We will add full portal functionality in subsequent PRs.
=> Admin Panel

components/Channel/StreamInfo.vue, components/StreamInfo.vue, components/User.vue, components/profile/ShowStreamKey.vue, layouts/default.vue, nuxt.config.js, package-lock.json, package.json
Adds [`@nuxtjs/dot-env`](https://github.com/nuxt-community/dotenv-module) to the project.
Injects version number into env.
Adds version number to footer.
=> Add .env support

components/Chat/index.vue
Adds hidden command to enable experimental filters for TTS that will strip out extra unicode and emoji characters (prevents emoji walls clogging TTS), and adds basic profanity filters.
=> Create TTS Sanity Filters

components/Chat/ChatInput.vue, components/Chat/ChatOverflowMenu.vue, components/Chat/index.vue, components/UserList.vue, layouts/default.vue, nuxt.config.js, package-lock.json, package.json, pages/_watch/index.vue, pages/index.vue, pages/report.vue, plugins/firebase.js, plugins/pwa.client.js, plugins/sw-hook.js, static/bitwave-notifications-sw.js, static/bitwave-offline-sw.js, store/chat.js, store/index.js
Improving caching & caching strategies to reduce server load
=> SSR improvements

.gitignore, Dockerfile, bitwave-deployment.yaml, bitwave-pod.yaml, bitwave-service.yaml, docker-compose.yml, package.json, pages/_watch/index.vue, pages/chat/_room.vue, pages/embed/_id.vue, pages/index.vue, pages/overlay/chat/_id.vue, pages/streamers.vue, store/index.js
Dockerize bitwave front end code and create Kubernates `yaml` files required for auto scaling.
=> [FEAT] Kubernates Auto Scaling

components/Chat/ChatMessages.vue, components/StreamGrid.vue, nuxt.config.js, pages/_watch/index.vue, pages/chat/_room.vue, pages/embed/_id.vue, pages/index.vue, pages/streamers.vue, plugins/axiossr.js
Handle request timeouts when using axios in async data to prevent server from hanging when API calls fail.
=> [FEAT] axios request timeout

components/Chat/ChatOverflowMenu.vue, components/Chat/ChatSettings.vue, components/User.vue, nuxt.config.js, pages/_watch/index.vue, pages/login.vue, plugins/firebase-analytics.client.js, plugins/firebase.js
=> [FEAT] Firebase analytics

assets/js/time-ago.js, components/Channel/StreamArchives.vue, components/Channel/StreamInfo.vue, package-lock.json, package.json, pages/_watch/replay/_replay.vue, store/index.js
Adds a page to handle viewing stream replays.
Functionally complete, needs additional polish that depends on API updates though.
=> Add Stream Replays

package-lock.json, package.json
fixes: https://github.com/bitwave-tv/bitwave/issues/135
Use our fixed fork of video.js to fix issue with page freezing when in background.
=> Fix video.js freezing when tab is in background

package.json, pages/_watch/index.vue
Limit max player width relative to current viewport height. This should improve the experience on ultrawide monitors, and ensure stream title is always visible when viewing a stream.
=> Limit player height based on viewport height

nuxt.config.js, package-lock.json, package.json
Adds sentry integration to improve error logging
=> Improve error logging

components/Chat/ViewerList/viewers.vue, store/index.js
Once again, works on my machine.
=> Implemented persistance for global viewer list option; fixes #106

components/Chat/Chat.vue, components/Chat/ChatInput.vue, package-lock.json, package.json
Fixes #164
Fixes #156
Does not resolve issue regarding the chat input being modified from text-field to text-area.
=> Fix 164, Finialize PR 156
